#!/usr/bin/env python3
"""Turns third_party/fonts/*.ttf into one C++ translation unit.

The fonts have to be in the binary rather than beside it: the browser build has
no filesystem to read them from, and a desktop build that looked for them
relative to the working directory would break the moment it was launched from
somewhere else. Baking them in is the only arrangement that behaves the same on
both platforms.

Usage: embed_fonts.py <output.cpp> <font> [font ...]
"""

import os
import sys


def main():
    if len(sys.argv) < 3:
        sys.stderr.write("usage: embed_fonts.py <output.cpp> <font> [font ...]\n")
        return 1

    out_path = sys.argv[1]
    fonts = sorted(sys.argv[2:])

    parts = ['/* Generated by tools/embed_fonts.py - do not edit. */\n',
             '#include "fonts.h"\n\n']
    names = []

    for index, path in enumerate(fonts):
        with open(path, 'rb') as handle:
            data = handle.read()

        symbol = "FONT_%d" % index
        names.append((os.path.splitext(os.path.basename(path))[0], symbol, len(data)))

        parts.append("static const unsigned char %s[] = {" % symbol)
        # Wrapped so the generated file stays openable in an editor.
        chunks = []
        for offset in range(0, len(data), 20):
            row = data[offset:offset + 20]
            chunks.append(",".join("0x%02x" % byte for byte in row))
        # ",\n", not "\n": the rows are one array, and joining without the
        # separator silently produces a file that will not compile.
        parts.append(",\n".join(chunks))
        parts.append("};\n\n")

    parts.append("const EmbeddedFont OBC_FONTS[] = {\n")
    for name, symbol, size in names:
        parts.append('    { "%s", %s, %du },\n' % (name, symbol, size))
    parts.append("};\n\n")
    parts.append("const int OBC_FONT_COUNT = %d;\n" % len(names))

    text = "".join(parts)

    # Only rewrite when something changed, so a rebuild does not recompile
    # megabytes of byte arrays for nothing.
    if os.path.exists(out_path):
        with open(out_path, "r") as handle:
            if handle.read() == text:
                return 0

    with open(out_path, "w") as handle:
        handle.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
